# Generated by Django 5.2.4 on 2026-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetgoalmodel',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addexpenses',
            name='bill',
            field=models.FileField(blank=True, null=True, upload_to='Bills/'),
        ),
    ]
